media:
  input: src/assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: src/blog/posts
    media_folder: "" # deixa vazio para usar pasta do post
    public_folder: "" # deixa vazio também
    view:
      fields: [title, published, date, tags]
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: title, label: Title, type: string }
      - { name: siteDescription, label: Description, type: string }
      - { name: date, label: Date, type: date }
      
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [sustentabilidade, jiu-jitsu, aula de inglês, educação, voluntariado, inclusão social, depoimento, inglês, legalização, transparência, políticas públicas, esporte, missão, história]
          
      - name: cover
        label: Cover Image
        type: image
        required: false
        
      - { name: body, label: Body, type: text }
