media:
  input: src/assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: src/blog/posts
    media_folder: "" # deixa vazio para usar pasta do post
    public_folder: "" # deixa vazio também
    view:
      fields: [title, published, date, tags]
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: title, label: Title, type: string }
      - { name: siteDescription, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          max: 5
          collapsible: false
      - { name: body, label: Body, type: text }
