media:
  input: src/assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: src/blog/posts
    view:
      fields: [title, published, date]
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: info
    label: Info
    type: collection
    path: src/blog/info
    view:
      fields: [title, published, date]
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: minifeeds
    label: MiniFeeds
    type: collection
    path: src/blog/minifeeds
    view:
      fields: [title, published, date]
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: config
    label: Site settings
    type: file
    path: src/_data/config.json
    fields:
      - { name: siteName, label: Site Name, type: string }
      - { name: siteURL, label: Site URL, type: string }
      - { name: siteAuthor, label: Site Author, type: string }
      - { name: siteLang, label: Site Language, type: string }
      - { name: authorLink, label: Author Link, type: string }
      - { name: authorContact, label: Author Contact, type: string }
      - { name: siteSubDir, label: Site SubDir, type: string }