media:
  input: src/assets/images
  output: /assets/images
  use_relative_path: true

content:
  - name: posts
    label: Posts
    type: collection
    path: src/blog/posts
    fields:
      - { name: published, label: Published, type: boolean, default: true }
      - { name: date, label: Date, type: date }
      - { name: title, label: Title, type: string }
      - { name: siteDescription, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      - {name: tags, label: Tags, type: select, options:, multiple: true, values: [ Tech, News, Sports ]}

  - name: config
    label: Site settings
    type: file
    path: src/_data/config.json
    fields:
      - { name: siteName, label: Site Name, type: string }
      - { name: siteURL, label: Site URL, type: string }
      - { name: siteAuthor, label: Site Author, type: string }
      - { name: siteLang, label: Site Language, type: string }
      - { name: authorLink, label: Author Link, type: string }
      - { name: authorContact, label: Author Contact, type: string }
      - { name: siteSubDir, label: Site SubDir, type: string }
